import Cocoa

// MARK: - Icon Assets (Categories + Items + Helpers)
// Drop PNGs/SVGs into Assets.xcassets using these names.
// If an item isn't listed in ITEM_ASSETS, we auto-generate a slug so you still get an icon
// as long as your asset file uses the same slug (lowercased, spaces/symbols -> underscores).

@inline(__always)
public func slug(_ s: String) -> String {
    let lowered = s.lowercased()
    let replaced = lowered.replacingOccurrences(of: "[^a-z0-9]+", with: "_", options: .regularExpression)
    return replaced.trimmingCharacters(in: CharacterSet(charactersIn: "_"))
}

// MARK: Icon Assets
public let ICON_ASSETS: [String: String] = [
    // Production categories
    "assembling": "assembling_machine_3",
    "smelting": "electric_furnace",
    "foundry": "foundry",
    "chemistry": "chemical_plant",
    "pumping": "offshore_pump",
    "mining": "electric_mining_drill",
    "crushing": "crusher",
    "recycling": "recycler",
    "bio": "biolab",
    "cryogenic": "cryogenic_plant",
    "electromagnetic": "electromagnetic_plant",

    // Logistics / rail / lab
    "rail": "train_stop",
    "lab": "lab",

    // Utilities
    "power": "steam_turbine",
    "energy": "accumulator",

    // --- Plates, ores, bars ---
    "Iron Plate": "iron_plate",
    "Copper Plate": "copper_plate",
    "Steel Plate": "steel_plate",
    "Tungsten Plate": "tungsten_plate",
    "Lithium Plate": "lithium_plate",
    "Holmium Plate": "holmium_plate",
    "Iron Ore": "iron_ore",
    "Copper Ore": "copper_ore",
    "Tungsten Ore": "tungsten_ore",
    "Holmium Ore": "holmium_ore",
    "Uranium Ore": "uranium_ore",
    "Stone": "stone",
    "Stone Brick": "stone_brick",
    "Coal": "coal",
    "Plastic Bar": "plastic_bar",
    "Tungsten Carbide": "tungsten_carbide",
    "Uranium 235": "uranium_235",
    "Uranium 238": "uranium_238",
    "Lithium": "lithium",
    "Calcite": "calcite",
    "Carbon": "carbon",
    "Carbon Fiber": "carbon_fiber",
    "Scrap": "scrap",

    // --- Fluids ---
    "Water": "water",
    "Steam": "steam",
    "Heavy Oil": "heavy_oil",
    "Light Oil": "light_oil",
    "Petroleum Gas": "petroleum_gas",
    "Lubricant": "lubricant",
    "Sulfuric Acid": "sulfuric_acid",
    "Sulfur": "sulfur",
    "Ammonia": "ammonia",
    "Ammoniacal Solution": "ammoniacal_solution",
    "Ammoniacal Solution Separation": "ammoniacal_solution_separation",
    "Fluorine": "fluorine",
    "Lithium Brine": "lithium_brine",
    "Holmium Solution": "holmium_solution",
    "Electrolyte": "electrolyte",
    "Fluoroketone Cold": "fluoroketone_cold",
    "Fluoroketone Hot": "fluoroketone_hot",
    "Molten Iron": "molten_iron",
    "Molten Copper": "molten_copper",
    "Molten Iron from Lava": "molten_iron_from_lava",
    "Molten Copper from Lava": "molten_copper_from_lava",
    "Lava": "lava",
    "Ice": "ice",
    "Ice Melting": "ice_melting",
    "Ice Platform": "ice_platform",
    "Crude Oil": "crude_oil",

    // --- Oil Processing ---
    "Basic Oil Processing": "basic_oil_processing",
    "Advanced Oil Processing": "advanced_oil_processing",
    "Coal Liquefaction": "coal_liquefaction",
    "Simple Coal Liquefaction": "simple_coal_liquefaction",
    "Heavy Oil Cracking": "heavy_oil_cracking",
    "Light Oil Cracking": "light_oil_cracking",
    "Coal Synthesis": "coal_synthesis",
    "Acid Neutralisation": "acid_neutralisation",
    "Steam Condensation": "steam_condensation",
    

    // --- Barrels ---
    "Barrel": "barrel",
    "Empty Barrel": "empty_barrel",
    "Water Barrel": "water_barrel",
    "Empty Water Barrel": "empty_water_barrel",
    "Crude Oil Barrel": "crude_oil_barrel",
    "Empty Crude Oil Barrel": "empty_crude_oil_barrel",
    "Heavy Oil Barrel": "heavy_oil_barrel",
    "Empty Heavy Oil Barrel": "empty_heavy_oil_barrel",
    "Light Oil Barrel": "light_oil_barrel",
    "Empty Light Oil Barrel": "empty_light_oil_barrel",
    "Petroleum Gas Barrel": "petroleum_gas_barrel",
    "Empty Petroleum Gas Barrel": "empty_petroleum_gas_barrel",
    "Lubricant Barrel": "lubricant_barrel",
    "Empty Lubricant Barrel": "empty_lubricant_barrel",
    "Sulfuric Acid Barrel": "sulfuric_acid_barrel",
    "Empty Sulfuric Acid Barrel": "empty_sulfuric_acid_barrel",
    "Fluoroketone Cold Barrel": "fluoroketone_cold_barrel",
    "Empty Fluoroketone Cold Barrel": "empty_fluoroketone_cold_barrel",
    "Fluoroketone Hot Barrel": "fluoroketone_hot_barrel",
    "Empty Fluoroketone Hot Barrel": "empty_fluoroketone_hot_barrel",

    // --- Components ---
    "Iron Stick": "iron_stick",
    "Iron Gear Wheel": "iron_gear_wheel",
    "Copper Cable": "copper_cable",
    "Pipe": "pipe",
    "Pipe to Ground": "pipe_to_ground",
    "Engine Unit": "engine_unit",
    "Electric Engine Unit": "electric_engine_unit",
    "Flying Robot Frame": "flying_robot_frame",
    "Advanced Circuit": "advanced_circuit",
    "Electronic Circuit": "electronic_circuit",
    "Processing Unit": "processing_unit",
    "Quantum Processor": "quantum_processor",
    "Low Density Structure": "low_density_structure",
    "Accumulator": "accumulator",
    "Battery": "battery",
    "Supercapacitor": "supercapacitor",
    "Superconductor": "superconductor",
    "Explosives": "explosives",
    "Solid Fuel": "solid_fuel",
    "Solid Fuel from Petroleum Gas": "solid_fuel_from_petroleum_gas",
    "Solid Fuel from Light Oil": "solid_fuel_from_light_oil",
    "Solid Fuel from Heavy Oil": "solid_fuel_from_heavy_oil",
    "Solid Fuel from Ammonia": "solid_fuel_from_ammonia",
    "Rocket Control Unit": "rocket_control_unit",
    "Repair Pack": "repair_pack",

    // --- Casting Recipes ---
    "Casting Iron": "casting_iron",
    "Casting Copper": "casting_copper",
    "Casting Steel": "casting_steel",
    "Casting Iron Gear Wheel": "casting_iron_gear_wheel",
    "Casting Iron Stick": "casting_iron_stick",
    "Casting Copper Cable": "casting_copper_cable",
    "Casting Pipe": "casting_pipe",
    "Casting Pipe to Ground": "casting_pipe_to_ground",
    "Casting Low Density Structure": "casting_low_density_structure",

    // --- Modules ---
    "Speed Module": "speed_module",
    "Speed Module 2": "speed_module_2",
    "Speed Module 3": "speed_module_3",
    "Productivity Module": "productivity_module",
    "Productivity Module 2": "productivity_module_2",
    "Productivity Module 3": "productivity_module_3",
    "Efficiency Module": "efficiency_module",
    "Efficiency Module 2": "efficiency_module_2",
    "Efficiency Module 3": "efficiency_module_3",
    "Quality Module": "quality_module",
    "Quality Module 2": "quality_module_2",
    "Quality Module 3": "quality_module_3",

    // --- Machines / buildings ---
    "Assembling Machine 1": "assembling_machine_1",
    "Assembling Machine 2": "assembling_machine_2",
    "Assembling Machine 3": "assembling_machine_3",
    "Stone Furnace": "stone_furnace",
    "Steel Furnace": "steel_furnace",
    "Electric Furnace": "electric_furnace",
    "Chemical Plant": "chemical_plant",
    "Oil Refinery": "oil_refinery",
    "Electromagnetic Plant": "electromagnetic_plant",
    "Cryogenic Plant": "cryogenic_plant",
    "Crusher": "crusher",
    "Foundry": "foundry",
    "Lab": "lab",
    "Biolab": "biolab",
    "Biochamber": "biochamber",
    "Offshore Pump": "offshore_pump",
    "Pumpjack": "pumpjack",
    "Pump": "pump",
    "Electric Mining Drill": "electric_mining_drill",
    "Burner Mining Drill": "burner_mining_drill",
    "Big Mining Drill": "big_mining_drill",
    "Lightning Collector": "lightning_collector",
    "Lightning Rod": "lightning_rod",
    "Asteroid Collector": "asteroid_collector",
    "Recycler": "recycler",
    "Heating Tower": "heating_tower",
    "Centrifuge": "centrifuge",
    "Agricultural Tower": "agricultural_tower",
    "Beacon": "beacon",
    "Radar": "radar",
    "Storage Tank": "storage_tank",
    "Boiler": "boiler",
    "Heat Pipe": "heat_pipe",
    "Heat Interface": "heat_interface",
    "Heat Exchanger": "heat_exchanger",

    // --- Nuclear ---
    "Nuclear Reactor": "nuclear_reactor",
    "Nuclear Fuel": "nuclear_fuel",
    "Nuclear Fuel Reprocessing": "nuclear_fuel_reprocessing",
    "Uranium Fuel Cell": "uranium_fuel_cell",
    "Depleted Uranium Fuel Cell": "depleted_uranium_fuel_cell",
    "Used Up Uranium Fuel Cell": "used_up_uranium_fuel_cell",
    "Uranium Processing": "uranium_processing",
    "Kovarex Enrichment Process": "kovarex_enrichment_process",
    "Fusion Reactor": "fusion_reactor",
    "Fusion Generator": "fusion_generator",
    "Fusion Power Cell": "fusion_power_cell",

    // --- Logistics / chests / belts ---
    "Active Provider Chest": "active_provider_chest",
    "Passive Provider Chest": "passive_provider_chest",
    "Buffer Chest": "buffer_chest",
    "Requester Chest": "requester_chest",
    "Storage Chest": "storage_chest",
    "Steel Chest": "steel_chest",
    "Iron Chest": "iron_chest",
    "Wooden Chest": "wooden_chest",
    "Infinity Chest": "infinity_chest",
    "Infinity Pipe": "infinity_pipe",

    "Transport Belt": "transport_belt",
    "Underground Belt": "underground_belt",
    "Splitter": "splitter",
    "Fast Transport Belt": "fast_transport_belt",
    "Fast Underground Belt": "fast_underground_belt",
    "Fast Splitter": "fast_splitter",
    "Express Transport Belt": "express_transport_belt",
    "Express Underground Belt": "express_underground_belt",
    "Express Splitter": "express_splitter",
    "Turbo Transport Belt": "turbo_transport_belt",
    "Turbo Underground Belt": "turbo_underground_belt",
    "Turbo Splitter": "turbo_splitter",
    "Loader": "loader",

    // --- Inserters ---
    "Burner Inserter": "burner_inserter",
    "Inserter": "inserter",
    "Long Handed Inserter": "long_handed_inserter",
    "Fast Inserter": "fast_inserter",
    "Bulk Inserter": "bulk_inserter",
    "Stack Inserter": "stack_inserter",

    // --- Robots ---
    "Construction Robot": "construction_robot",
    "Logistic Robot": "logistic_robot",
    "Roboport": "roboport",

    // --- Power ---
    "Steam Engine": "steam_engine",
    "Steam Turbine": "steam_turbine",
    "Solar Panel": "solar_panel",

    // --- Rail ---
    "Train Stop": "train_stop",
    "Rail": "rail",
    "Straight Rail": "straight_rail",
    "Rail Signal": "rail_signal",
    "Rail Chain Signal": "rail_chain_signal",
    "Rail Ramp": "rail_ramp",
    "Rail Support": "rail_support",
    "Locomotive": "locomotive",
    "Cargo Wagon": "cargo_wagon",
    "Fluid Wagon": "fluid_wagon",
    "Artillery Wagon": "artillery_wagon",

    // --- Vehicles ---
    "Car": "car",
    "Tank": "tank",
    "Spidertron": "spidertron",

    // --- Science packs ---
    "Automation Science Pack": "automation_science_pack",
    "Logistic Science Pack": "logistic_science_pack",
    "Military Science Pack": "military_science_pack",
    "Chemical Science Pack": "chemical_science_pack",
    "Production Science Pack": "production_science_pack",
    "Utility Science Pack": "utility_science_pack",
    "Space Science Pack": "space_science_pack",
    "Agricultural Science Pack": "agricultural_science_pack",
    "Electromagnetic Science Pack": "electromagnetic_science_pack",
    "Metallurgic Science Pack": "metallurgic_science_pack",
    "Cryogenic Science Pack": "cryogenic_science_pack",
    "Promethium Science Pack": "promethium_science_pack",

    // --- Bio chain ---
    "Bioflux": "bioflux",
    "Nutrients": "nutrients",
    "Nutrients from Spoilage": "nutrients_from_spoilage",
    "Nutrients from Yumako Mash": "nutrients_from_yumako_mash",
    "Nutrients from Bioflux": "nutrients_from_bioflux",
    "Nutrients from Fish": "nutrients_from_fish",
    "Nutrients from Biter Egg": "nutrients_from_biter_egg",
    "Jelly": "jelly",
    "Jellynut": "jellynut",
    "Jellynut Seed": "jellynut_seed",
    "Jellynut Processing": "jellynut_processing",
    "Yumako": "yumako",
    "Yumako Seed": "yumako_seed",
    "Yumako Mash": "yumako_mash",
    "Yumako Processing": "yumako_processing",
    "Pentapod Egg": "pentapod_egg",
    "Raw Fish": "raw_fish",
    "Fish Breeding": "fish_breeding",
    "Spoilage": "spoilage",
    "Burnt Spoilage": "burnt_spoilage",
    "Tree Seed": "tree_seed",
    "Wood": "wood",
    "Wood Processing": "wood_processing",
    "Artificial Jellynut Soil": "artificial_jellynut_soil",
    "Artificial Yumako Soil": "artificial_yumako_soil",
    "Overgrowth Jellynut Soil": "overgrowth_jellynut_soil",
    "Overgrowth Yumako Soil": "overgrowth_yumako_soil",
    "Captive Biter Spawner": "captive_biter_spawner",
    "Biter Egg": "biter_egg",
    "Iron Bacteria": "iron_bacteria",
    "Iron Bacteria Cultivation": "iron_bacteria_cultivation",
    "Copper Bacteria": "copper_bacteria",
    "Copper Bacteria Cultivation": "copper_bacteria_cultivation",
    "Bioplastic": "bioplastic",
    "Biolubricant": "biolubricant",
    "Biosulfur": "biosulfur",
    "Rocket Fuel from Jelly": "rocket_fuel_from_jelly",

    // --- Weapons / ammo ---
    "Pistol": "pistol",
    "Submachine Gun": "submachine_gun",
    "Shotgun": "shotgun",
    "Combat Shotgun": "combat_shotgun",
    "Rocket Launcher": "rocket_launcher",
    "Flamethrower": "flamethrower",
    "Teslagun": "teslagun",
    "Railgun": "railgun",
    "Grenade": "grenade",
    "Cluster Grenade": "cluster_grenade",
    "Poison Capsule": "poison_capsule",
    "Slowdown Capsule": "slowdown_capsule",
    "Defender Capsule": "defender_capsule",
    "Distractor Capsule": "distractor_capsule",
    "Destroyer Capsule": "destroyer_capsule",
    "Capture Robot Rocket": "capture_robot_rocket",
    "Firearm Magazine": "firearm_magazine",
    "Piercing Rounds Magazine": "piercing_rounds_magazine",
    "Uranium Rounds Magazine": "uranium_rounds_magazine",
    "Shotgun Shell": "shotgun_shell",
    "Piercing Shotgun Shell": "piercing_shotgun_shell",
    "Cannon Shell": "cannon_shell",
    "Explosive Cannon Shell": "explosive_cannon_shell",
    "Uranium Cannon Shell": "uranium_cannon_shell",
    "Explosive Uranium Cannon Shell": "explosive_uranium_cannon_shell",
    "Artillery Shell": "artillery_shell",
    "Rocket": "rocket",
    "Explosive Rocket": "explosive_rocket",
    "Atomic Bomb": "atomic_bomb",
    "Flamethrower Ammo": "flamethrower_ammo",
    "Tesla Ammo": "tesla_ammo",
    "Railgun Ammo": "railgun_ammo",
    "Land Mine": "land_mine",
    "Cliff Explosives": "cliff_explosives",

    // --- Turrets ---
    "Gun Turret": "gun_turret",
    "Laser Turret": "laser_turret",
    "Flamethrower Turret": "flamethrower_turret",
    "Artillery Turret": "artillery_turret",
    "Tesla Turret": "tesla_turret",
    "Railgun Turret": "railgun_turret",
    "Rocket Turret": "rocket_turret",

    // --- Armor ---
    "Light Armor": "light_armor",
    "Heavy Armor": "heavy_armor",
    "Modular Armor": "modular_armor",
    "Power Armor": "power_armor",
    "Power Armor Mk2": "power_armor_mk2",
    "Mech Armor": "mech_armor",

    // --- Equipment ---
    "Solar Panel Equipment": "solar_panel_equipment",
    "Fission Reactor Equipment": "fission_reactor_equipment",
    "Fusion Reactor Equipment": "fusion_reactor_equipment",
    "Battery Equipment": "battery_equipment",
    "Battery Mk2 Equipment": "battery_mk2_equipment",
    "Battery Mk3 Equipment": "battery_mk3_equipment",
    "Belt Immunity Equipment": "belt_immunity_equipment",
    "Exoskeleton Equipment": "exoskeleton_equipment",
    "Personal Roboport Equipment": "personal_roboport_equipment",
    "Personal Roboport Mk2 Equipment": "personal_roboport_mk2_equipment",
    "Night Vision Equipment": "night_vision_equipment",
    "Toolbelt Equipment": "toolbelt_equipment",
    "Energy Shield Equipment": "energy_shield_equipment",
    "Energy Shield Mk2 Equipment": "energy_shield_mk2_equipment",
    "Personal Laser Defense Equipment": "personal_laser_defense_equipment",
    "Discharge Defense Equipment": "discharge_defense_equipment",
    "Portable Solar Panel": "portable_solar_panel",
    "Portable Fusion Reactor": "portable_fusion_reactor",

    // --- Space / Asteroids ---
    "Rocket Fuel": "rocket_fuel",
    "Ammonia Rocket Fuel": "ammonia_rocket_fuel",
    "Rocket Part": "rocket_part",
    "Rocket Silo": "rocket_silo",
    "Space Platform Foundation": "space_platform_foundation",
    "Space Platform Starter Pack": "space_platform_starter_pack",
    "Space Platform Hub": "space_platform_hub",
    "Satellite": "satellite",
    "Cargo Bay": "cargo_bay",
    "Cargo Landing Pad": "cargo_landing_pad",
    "Thruster": "thruster",
    "Thruster Fuel": "thruster_fuel",
    "Thruster Oxidizer": "thruster_oxidizer",
    "Advanced Thruster Fuel": "advanced_thruster_fuel",
    "Advanced Thruster Oxidizer": "advanced_thruster_oxidizer",
    "Foundation": "foundation",
    "Metallic Asteroid Chunk": "metallic_asteroid_chunk",
    "Carbonic Asteroid Chunk": "carbonic_asteroid_chunk",
    "Oxide Asteroid Chunk": "oxide_asteroid_chunk",
    "Promethium Asteroid Chunk": "promethium_asteroid_chunk",
    "Metallic Asteroid Crushing": "metallic_asteroid_crushing",
    "Carbonic Asteroid Crushing": "carbonic_asteroid_crushing",
    "Oxide Asteroid Crushing": "oxide_asteroid_crushing",
    "Advanced Metallic Asteroid Crushing": "advanced_metallic_asteroid_crushing",
    "Advanced Carbonic Asteroid Crushing": "advanced_carbonic_asteroid_crushing",
    "Advanced Oxide Asteroid Crushing": "advanced_oxide_asteroid_crushing",
    "Metallic Asteroid Reprocessing": "metallic_asteroid_reprocessing",
    "Carbonic Asteroid Reprocessing": "carbonic_asteroid_reprocessing",
    "Oxide Asteroid Reprocessing": "oxide_asteroid_reprocessing",

    // --- Concrete ---
    "Concrete": "concrete",
    "Concrete from Molten Iron": "concrete_from_molten_iron",
    "Hazard Concrete": "hazard_concrete",
    "Refined Concrete": "refined_concrete",
    "Refined Hazard Concrete": "refined_hazard_concrete",

    // --- Circuit Network ---
    "Arithmetic Combinator": "arithmetic_combinator",
    "Decider Combinator": "decider_combinator",
    "Selector Combinator": "selector_combinator",
    "Constant Combinator": "constant_combinator",
    "Power Switch": "power_switch",
    "Programmable Speaker": "programmable_speaker",
    "Display Panel": "display_panel",
    "Green Wire": "green_wire",
    "Red Wire": "red_wire",

    // --- Walls and Defense ---
    "Stone Wall": "stone_wall",
    "Wall": "wall",
    "Gate": "gate",

    // --- Misc ---
    "Lamp": "lamp",
    "Small Lamp": "small_lamp",
    "Landfill": "landfill",
    "Scrap Recycling": "scrap_recycling",
    "Blueprint": "blueprint",
    "Blueprint Book": "blueprint_book",
    "Deconstruction Planner": "deconstruction_planner",
    "Upgrade Planner": "upgrade_planner"
]

/// Return the best image asset name for any item or category.
@inline(__always)
public func iconAssetName(for name: String) -> String {
    if let item = ICON_ASSETS[name] { return item }
    if let cat = ICON_ASSETS[name] { return cat }
    return slug(name) // graceful fallback if not explicitly listed
}
